[package]
name = "archipelago_rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_repr = "0.1"
thiserror = "2.0.12"
futures-util = { version = "0.3", default-features = false, features = ["sink"] }
tokio = "1.45.0"
tokio-tungstenite = { git = "https://github.com/snapview/tokio-tungstenite", rev = "6943e3a97c77e7aff053478b78a803f84c7d6345", features = ["native-tls"] }
tungstenite = { git = "https://github.com/snapview/tungstenite-rs", rev = "32981b5babcae64ff1cb4d597b6647edfee2f948", features = ["deflate"] }
log = { version = "0.4.27" }

[dev-dependencies]
anyhow = "1.0"
tokio = { version = "1.45.0", features = ["rt", "macros"] }
