[package]
name = "archipelago_rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_repr = "0.1"
thiserror = "2.0.12"
tokio = "1.45.0"
tokio-native-tls = "0.3.1"
bytes = "1.10.1"
ratchet_core = { version = "1.2.1", features = ["split"] }
ratchet_rs = { version = "1.2.1", features = ["deflate", "split"] }

[dev-dependencies]
anyhow = "1.0"
tokio = { version = "1.45.0", features = ["rt", "macros"] }
